services:
  db:
    image: mysql:latest
    container_name: lmsdb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lms_db
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: